name: Docker Image CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build-image]
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
      run: |
        IMAGE_TAG=multi:latest
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV #Para permitir que la variable sea accesible entre distintos steps
        
    - name: Save image as tar
      run: docker save $IMAGE_TAG -o multi.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: multi.tar


